version: '3'

services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    ports:
      - 3000:3000 # porta padrão da aplicação
    command: dev
    env_file:
      - ./client/.env
    volumes:
      # vincula pasta local com a dentro do container
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    depends_on:
      - backend
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - 3001:3001 # porta padrão da aplicação
    command: dev # roda aplicação com nodemon
    volumes:
      # vincula pasta local com a dentro do container
      - ./server/src:/app/server/src
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.32
    container_name: server_db
    env_file:
      - ./server/.env
    ports:
      - 3306:3306
    healthcheck:
      # Deve aguardar o banco ficar operacional
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - ./database:/docker-entrypoint-initdb.d
